# Generated by Django 2.1.15 on 2024-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0002_kategoriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
