# Generated by Django 4.2.9 on 2024-02-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0004_item_alter_cars_id_alter_cars_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='categori',
            field=models.ManyToManyField(to='sayfalar.kategoriler'),
        ),
    ]
