# Generated by Django 4.2.9 on 2024-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0005_cars_categori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='categori',
        ),
    ]
