# Generated by Django 4.2.9 on 2024-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0008_remove_cars_home_categori_alter_cars_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
