# Generated by Django 4.2.9 on 2024-02-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0009_alter_categories_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='Home_Categori',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='imageUrl',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description',
            new_name='text',
        ),
    ]
