# Generated by Django 4.2.9 on 2024-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0010_rename_home_categori_cars_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('icon', models.TextField()),
                ('title', models.TextField()),
                ('textone', models.TextField()),
                ('texttwo', models.TextField()),
            ],
        ),
    ]
