# Generated by Django 4.2.9 on 2024-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0011_servicesproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrerrProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('buttonText', models.DateField()),
            ],
        ),
    ]
