# Generated by Django 4.2.9 on 2024-02-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0012_carrerrproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carrerrProduct',
            new_name='careerProduct',
        ),
    ]
