# Generated by Django 4.2.9 on 2024-02-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0013_rename_carrerrproduct_careerproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='project',
        ),
    ]
