# Generated by Django 4.2.9 on 2024-03-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0017_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
