# Generated by Django 4.2.9 on 2024-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0018_alter_project_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
