# Generated by Django 4.2.9 on 2024-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0020_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
