# Generated by Django 4.2.9 on 2024-03-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0022_rename_img_uploadmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
